# Generated by Django 3.2.3 on 2023-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0014_auto_20230721_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
